### ISSUE TITLE
Error in resampling for 'pr' after merge

### ISSUE THREAD

**Issue by SimonTreu** [ISI-MIP/isi-cfact#54]
/home/sitreu/anaconda/envs/isi-cfact/bin/python /home/sitreu/Documents/PIK/CounterFactuals/isi-cfact/run_single_cell.py
Version 0+untagged.645.gb3f4c31.dirty
Using PrecipitationLongtermYearlycycle distribution model.
Mask 14970 values below lower bound.
Min, max after scaling: 1.500186461872905e-05 21.77238812108605
4017 data points used from originally 40177 datapoints.
['pbern_fourier_coeffs_logodds__', 'pbern_b_const_logodds__', 'b_scale_logodds__', 'pbern_a_logodds__', 'mu_fourier_coeffs_log__', 'mu_b_const_log__', 'am_log__', 'sigma_fourier_coeffs_log__', 'sigma_b_const_log__', 'as_log__', 'pbern_fourier_coeffs', 'pbern_b_const', 'b_scale', 'b_pbern', 'pbern_a', 'a_pbern', 'pbern', 'mu_fourier_coeffs', 'mu_b_const', 'b_mu', 'am', 'a_mu', 'mu', 'sigma_fourier_coeffs', 'sigma_b_const', 'b_sigma', 'as', 'a_sigma', 'sigma']
Successfully loaded sampled data from
/home/sitreu/Documents/PIK/CounterFactuals/isi-cfact/output/isi-cfact/traces/pr/lat_-20.25/lon-49.75
Skip this for sampling.
Trace is not complete due to masked data. Resample missing.
Trace length: 2494 Dataframe length 40177
Traceback (most recent call last):
  File "/home/sitreu/anaconda/envs/isi-cfact/lib/python3.7/site-packages/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
ValueError: Input dimension mis-match. (input[0].shape[0] = 40177, input[3].shape[0] = 4017)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sitreu/Documents/PIK/CounterFactuals/isi-cfact/run_single_cell.py", line 66, in <module>
    df_with_cfact = estimator.estimate_timeseries(dff, trace, datamin, scale)
  File "/home/sitreu/Documents/PIK/CounterFactuals/isi-cfact/icounter/estimator.py", line 133, in estimate_timeseries
    trace_for_qm = self.statmodel.resample_missing(trace, df, subtrace, self.model, self.progressbar)
  File "/home/sitreu/Documents/PIK/CounterFactuals/isi-cfact/icounter/models.py", line 31, in resample_missing
    trace[-subtrace:],
  File "/home/sitreu/anaconda/envs/isi-cfact/lib/python3.7/site-packages/pymc3/backends/base.py", line 292, in __getitem__
    return self._slice(idx)
  File "/home/sitreu/anaconda/envs/isi-cfact/lib/python3.7/site-packages/pymc3/backends/base.py", line 496, in _slice
    new_traces = [trace._slice(slice) for trace in self._straces.values()]
  File "/home/sitreu/anaconda/envs/isi-cfact/lib/python3.7/site-packages/pymc3/backends/base.py", line 496, in <listcomp>
    new_traces = [trace._slice(slice) for trace in self._straces.values()]
  File "/home/sitreu/anaconda/envs/isi-cfact/lib/python3.7/site-packages/pymc3/backends/ndarray.py", line 287, in _slice
    sliced = NDArray(model=self.model, vars=self.vars)
  File "/home/sitreu/anaconda/envs/isi-cfact/lib/python3.7/site-packages/pymc3/backends/ndarray.py", line 160, in __init__
    super().__init__(name, model, vars, test_point)
  File "/home/sitreu/anaconda/envs/isi-cfact/lib/python3.7/site-packages/pymc3/backends/base.py", line 60, in __init__
    var_values = list(zip(self.varnames, self.fn(test_point)))
  File "/home/sitreu/anaconda/envs/isi-cfact/lib/python3.7/site-packages/pymc3/model.py", line 1173, in __call__
    return self.f(**state)
  File "/home/sitreu/anaconda/envs/isi-cfact/lib/python3.7/site-packages/theano/compile/function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/sitreu/anaconda/envs/isi-cfact/lib/python3.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/sitreu/anaconda/envs/isi-cfact/lib/python3.7/site-packages/six.py", line 695, in reraise
    raise value.with_traceback(tb)
  File "/home/sitreu/anaconda/envs/isi-cfact/lib/python3.7/site-packages/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
ValueError: Input dimension mis-match. (input[0].shape[0] = 40177, input[3].shape[0] = 4017)
Apply node that caused the error: Elemwise{Composite{(((i0 / i1) - ((i0 / i2) + ((i3 * i0) / i4))) + i5 + i6)}}[(0, 3)](gmt, Elemwise{Composite{(i0 + exp((-i1)))}}.0, Elemwise{Composite{(i0 + exp((-i1)))}}.0, Elemwise{Composite{(i0 - (i0 / i1))}}[(0, 0)].0, Elemwise{Composite{((i0 + exp((-i1))) * i2)}}[(0, 2)].0, InplaceDimShuffle{x}.0, Elemwise{true_div,no_inplace}.0)
Toposort index: 53
Inputs types: [TensorType(float64, vector), TensorType(float64, (True,)), TensorType(float64, (True,)), TensorType(float64, vector), TensorType(float64, (True,)), TensorType(float64, (True,)), TensorType(float64, vector)]
Inputs shapes: [(40177,), (1,), (1,), (4017,), (1,), (1,), (4017,)]
Inputs strides: [(8,), (8,), (8,), (8,), (8,), (8,), (8,)]
Inputs values: ['not shown', array([2.]), array([2.]), 'not shown', array([4.42253746]), array([0.5]), 'not shown']
Outputs clients: [['output']]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

Process finished with exit code 1

**Comment by SimonTreu** [comment]
trace[-subtrace:] 
throws error after pm.set_data({"gmt": df["gmt_scaled"].values}). Does this change the trace variable maybe? 
Why did that error not appear earlier?
Quick fix: use trace_for_qm variable

**Comment by SimonTreu** [comment]
Thats not the reason, xf0 and xf0v must also be reset. 
have to check how to make it consistent

**Comment by SimonTreu** [comment]
fixed the issue with xf0 and xf0v reset in the resampel function. But there is still the same error. This error only appears for PrecipLongtermYearlycycle. Maybe it needs no fix because this implementation is anyways irrelevant

**Comment by SimonTreu** [comment]
Probably was because of an old saved trace that was loaded but did not fit the model
